/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Felipe
 */
public class Layout extends javax.swing.JFrame {

    UsuarioVista vistaUsuario = null;
    Categoriasvista vistaCategorias = null;
    PreguntasVita vistaPreguntas = null;
    Juego vistaJuego = null;
    
    
    public Layout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        usuarioMenuItem = new javax.swing.JMenuItem();
        categoriaMenuItem = new javax.swing.JMenuItem();
        PreguntaMenuItem = new javax.swing.JMenuItem();
        iniciarJuegoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quien quiere ser millonario");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Opciones");

        usuarioMenuItem.setMnemonic('o');
        usuarioMenuItem.setText("Usuarios");
        usuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(usuarioMenuItem);

        categoriaMenuItem.setMnemonic('s');
        categoriaMenuItem.setText("Categorias");
        categoriaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(categoriaMenuItem);

        PreguntaMenuItem.setMnemonic('a');
        PreguntaMenuItem.setText("Preguntas");
        PreguntaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreguntaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(PreguntaMenuItem);

        iniciarJuegoMenuItem.setMnemonic('x');
        iniciarJuegoMenuItem.setText("Iniciar Juego");
        iniciarJuegoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJuegoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(iniciarJuegoMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarJuegoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarJuegoMenuItemActionPerformed
        if(vistaJuego == null || vistaJuego.isClosed()) {
            this.vistaJuego = new Juego();
            this.desktopPane.add(vistaJuego);            
        }
        vistaJuego.setVisible(true);
    }//GEN-LAST:event_iniciarJuegoMenuItemActionPerformed

    private void usuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuItemActionPerformed
        if(vistaUsuario == null || vistaUsuario.isClosed()) {
            this.vistaUsuario = new UsuarioVista();
            this.desktopPane.add(vistaUsuario);            
        }
        vistaUsuario.setVisible(true);
    }//GEN-LAST:event_usuarioMenuItemActionPerformed

    private void categoriaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaMenuItemActionPerformed
        if(vistaCategorias == null || vistaCategorias.isClosed()) {
            this.vistaCategorias = new Categoriasvista();
            this.desktopPane.add(vistaCategorias);            
        }
        vistaCategorias.setVisible(true);
    }//GEN-LAST:event_categoriaMenuItemActionPerformed

    private void PreguntaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreguntaMenuItemActionPerformed
        if(vistaPreguntas == null || vistaPreguntas.isClosed()) {
            this.vistaPreguntas = new PreguntasVita();
            this.desktopPane.add(vistaPreguntas);            
        }
        vistaPreguntas.setVisible(true);
    }//GEN-LAST:event_PreguntaMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PreguntaMenuItem;
    private javax.swing.JMenuItem categoriaMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem iniciarJuegoMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem usuarioMenuItem;
    // End of variables declaration//GEN-END:variables

}
